Repository bimdata/platform, pull requests merged in 2024-09, with the labels that each got.

#466 feat: refactor permission handling
  src/components/specific/files/all-files-table/AllFilesTable.vue
  src/components/specific/files/files-manager/FilesManager.vue
  src/components/specific/files/files-manager/files-action-bar/FilesActionBar.vue
  src/components/specific/files/files-manager/files-manager-actions/FilesManagerActions.vue
  src/components/specific/files/files-manager/files-manager-onboarding/FilesManagerOnboarding.vue
  src/components/specific/files/files-table/file-actions-cell/FileActionsCell.scss
  src/components/specific/files/files-table/file-actions-cell/FileActionsCell.vue
  src/components/specific/files/files-table/file-name-cell/FileNameCell.vue
  src/components/specific/files/files-table/file-path-cell/FilePathCell.vue
  src/components/specific/files/files-table/file-type-cell/FileTypeCell.vue
  src/components/specific/files/folder-access-manager/FolderAccessManager.scss
  src/components/specific/files/folder-selector/FolderSelector.vue
  src/components/specific/files/folder-table/FoldersTable.vue
  src/components/specific/groups/group-import/GroupImport.vue
  src/components/specific/models/model-location/ModelLocation.vue
  src/components/specific/models/models-card/models-card-model-preview/ModelsCardModelPreview.vue
  src/components/specific/models/models-manager/generic-models-manager/GenericModelsManager.vue
  src/components/specific/models/models-manager/models-action-bar/ModelsActionBar.vue
  src/components/specific/models/models-manager/pdf-manager/PDFManager.vue
  src/components/specific/models/models-overview/models-overview-onboarding/ModelsOverviewOnboarding.vue
  src/components/specific/models/models-table/model-actions-cell/ModelActionsCell.vue
  src/components/specific/projects/project-card/ProjectCard.vue
  src/components/specific/projects/project-card/project-card-action-menu/ProjectCardActionMenu.vue
  src/components/specific/spaces/space-card/SpaceCard.vue
  src/components/specific/spaces/space-card/space-card-action-menu/SpaceCardActionMenu.vue
  src/components/specific/users/project-users-manager/ProjectUsersManager.vue
  src/components/specific/users/project-users-manager/users-manager-onboarding/UsersManagerOnboarding.vue
  src/components/specific/users/user-card/UserCard.vue
  src/components/specific/versioning/versioning-doc/VersioningDoc.vue
  src/components/specific/versioning/versioning-main/VersioningMain.vue
  src/components/specific/visa/visa-summary/VisaSummary.vue
  src/components/specific/visa/visa-summary/visa-comments/VisaComments.vue
  src/config/models.js
  src/state/groups.js
  src/state/mappers.js
  src/state/projects.js
  src/state/spaces.js
  src/state/user.js
  src/utils/file-structure.js
  src/utils/projects.js
  src/utils/spaces.js
  src/utils/users.js
  src/views/project-board/ProjectBoard.vue
  src/views/project-board/project-bcf/ProjectBcf.vue
  src/views/project-board/project-files/ProjectFiles.vue
  src/views/project-board/project-overview/ProjectOverview.vue
  src/views/project-groups/ProjectGroups.vue
  src/views/space-board/SpaceBoard.vue
Labels: Architecture

#469 feat: improve folder access manager ui
  src/components/specific/files/folder-access-manager/FolderAccessManager.scss
  src/components/specific/files/folder-access-manager/FolderAccessManager.vue
  src/components/specific/files/folder-access-manager/FolderPermissionSelector.vue
  src/components/specific/files/folder-access-manager/folder-permission-selector/FolderPermissionSelector.scss
  src/components/specific/files/folder-access-manager/folder-permission-selector/FolderPermissionSelector.vue
  src/components/specific/files/folder-access-manager/group-permission-selector/GroupPermissionSelector.scss
  src/components/specific/files/folder-access-manager/group-permission-selector/GroupPermissionSelector.vue
  src/i18n/lang/en.json
  src/i18n/lang/es.json
  src/i18n/lang/fr.json
  src/i18n/lang/it.json
Labels: Styles / CSS / UI, Feature

#470 avoid api calls fos visas
  src/state/visa.js
Labels: Optimisation
